apiVersion: v1
kind: Namespace
metadata:
  name: modekeeper-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer
  namespace: default
  labels:
    app.kubernetes.io/name: modekeeper-demo-trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: modekeeper-demo-trainer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modekeeper-demo-trainer
    spec:
      containers:
      - name: trainer
        image: nginx:1.27.4
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
